### ISSUE TITLE
Injector timed out for Windows/System32/ntdll.dll

### ISSUE THREAD

**Issue by JosiahRaySmith** [tklengyel/drakvuf#1299]
Hello there,

New to this capability and using https://drakvuf-sandbox.readthedocs.io/ for the install process

Wondering if anyone has seen this before, or has some advice.  Occurs right after I activate the windows VM and is present while the VM is booted to the desktop.  draksetup test    shows everything OK.

`root@admin-DRAKVUF:~# draksetup postinstall
[2021-08-27 17:09:26,845][INFO] Cleaning up leftovers(if any)
[2021-08-27 17:09:26,846][INFO] Deleted /var/lib/drakrun/profiles/kernel.json
[2021-08-27 17:09:26,846][INFO] Ejecting installation CDs
[2021-08-27 17:09:27,072][INFO] Determined PDB GUID: 684da42a30cc450f81c535b4d18944b12
[2021-08-27 17:09:27,073][INFO] Determined kernel filename: ntkrpamp.pdb
[2021-08-27 17:09:27,073][INFO] Fetching PDB file...
[2021-08-27 17:09:27,080][DEBUG] Starting new HTTPS connection (1): msdl.microsoft.com:443
[2021-08-27 17:09:27,211][DEBUG] https://msdl.microsoft.com:443 "GET /download/symbols/ntkrpamp.pdb/684da42a30cc450f81c535b4d18944b12/ntkrpamp.pdb HTTP/1.1" 302 0
[2021-08-27 17:09:27,215][DEBUG] Starting new HTTPS connection (1): vsblobprodscussu5shard51.blob.core.windows.net:443
[2021-08-27 17:09:27,488][DEBUG] https://vsblobprodscussu5shard51.blob.core.windows.net:443 "GET /b-4712e0edc5a240eabf23330d7df68e77/6EACF8331C3D96544FB890CEDE4DB714C5EC3AC8A085F404301A577BCBE0B8F900.blob?sv=2019-07-07&sr=b&si=1&sig=qqEQzpDK38B9hcwboTAompdFx3OMdsAgBEWgUudW4P4%3D&spr=https&se=2021-08-28T22%3A25%3A55Z&rscl=x-e2eid-09606ade-23614c48-82246d12-b71f8826-session-e043a4a8-7e51439c-babbae79-675ce265 HTTP/1.1" 200 6933504
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.93M/6.93M [00:00<00:00, 15.4MiB/s]
[2021-08-27 17:09:27,946][INFO] Generating profile out of PDB file...
[2021-08-27 17:09:49,085][INFO] Saving profile...
[2021-08-27 17:09:49,087][INFO] Deleted /var/lib/drakrun/profiles/ntkrpamp.pdb
[2021-08-27 17:09:50,221][INFO] Saving runtime profile...
[2021-08-27 17:09:50,224][INFO] Saving VM snapshot...
[2021-08-27 17:09:50,224][INFO] Saving VM vm-0
Saving to /var/lib/drakrun/volumes/snapshot.sav new xl format (info 0x3/0x0/2034)
xc: info: Saving domain 12, type x86 HVM
xc: Frames: 1044480/1044480  100%
xc: End of stream: 0/0    0%
[2021-08-27 17:09:57,438][INFO] Snapshot was saved succesfully.
[2021-08-27 17:09:57,439][INFO] Snapshotting persistent memory...
[2021-08-27 17:09:57,588][INFO] Generated VM configuration for vm-1
[2021-08-27 17:09:57,657][INFO] Created bridge drak1
[2021-08-27 17:09:57,785][INFO] Bridge drak1 is up
Formatting '/var/lib/drakrun/volumes/vm-1.img', fmt=qcow2 size=107374182400 backing_file=/var/lib/drakrun/volumes/vm-0.img backing_fmt=qcow2 cluster_size=65536 lazy_refcounts=off refcount_bits=16
[2021-08-27 17:09:58,195][INFO] Restoring VM vm-1
Loading new save file /var/lib/drakrun/volumes/snapshot.sav (new xl fmt info 0x3/0x0/2034)
 Savefile contains xl domain config in JSON format
Parsing config from /etc/drakrun/configs/vm-1.cfg
xc: info: Found x86 HVM domain from Xen 4.15
xc: info: Restoring domain
xc: info: Restore successful
xc: info: XenStore: mfn 0xfeffc, dom 0, evt 1
xc: info: Console: mfn 0xfefff, dom 0, evt 2
[2021-08-27 17:10:04,179][INFO] Fetching rekall profile for Windows/System32/ntdll.dll
[2021-08-27 17:11:04,312][INFO] Already deleted /var/lib/drakrun/profiles/amd64_ntdll_profile
Traceback (most recent call last):
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 562, in create_rekall_profile
    cmd = injector.read_file(guest_dll_path, local_dll_path)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/injector.py", line 65, in read_file
    return subprocess.run(injector_cmd, timeout=timeout, capture_output=True)
  File "/usr/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1869, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.8/subprocess.py", line 1072, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['injector', '-o', 'json', '-d', 'vm-1', '-r', '/var/lib/drakrun/profiles/kernel.json', '-i', '1796', '-k', '0x185000', '-m', 'readfile', '-e', 'C:\\Windows\\System32\\ntdll.dll', '-B', '/var/lib/drakrun/profiles/amd64_ntdll_profile']' timed out after 60 seconds

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/draksetup", line 5, in <module>
    ds.main()
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 766, in postinstall
    create_missing_profiles()
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 819, in create_missing_profiles
    create_rekall_profile(injector, profile, True)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 598, in create_rekall_profile
    on_create_rekall_profile_failure(
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 546, in on_create_rekall_profile_failure
    raise Exception(f"[REQUIRED DLL] {msg}") from exception
Exception: [REQUIRED DLL] Injector timed out for Windows/System32/ntdll.dll
`

**Comment by JosiahRaySmith** [comment]
@tklengyel Do you mind a courtesy look?  Shall I try a different windows ISO?

**Comment by tklengyel** [comment]
For DRAKVUF Sandbox related issues please open an issue on the DRAKVUF Sandbox repo https://github.com/CERT-Polska/drakvuf-sandbox

**Comment by JosiahRaySmith** [comment]
https://github.com/CERT-Polska/drakvuf-sandbox/issues/635
