### ISSUE TITLE
dirwatch stability

### ISSUE THREAD

**Issue by zashraf1337** [tklengyel/drakvuf#161]
Crashed after spawning 15 clones (2 at a time) with stack trace

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f2757ea54b2 in _IO_vfprintf_internal (s=<optimized out>, format=<optimized out>, ap=ap@entry=0x7f2756168d58) at vfprintf.c:1642
1642    vfprintf.c: No such file or directory.
(gdb) where
#0  0x00007f2757ea54b2 in _IO_vfprintf_internal (s=<optimized out>, format=<optimized out>, ap=ap@entry=0x7f2756168d58) at vfprintf.c:1642
#1  0x00007f2757f6d706 in ___printf_chk (flag=1, format=<optimized out>) at printf_chk.c:35
#2  0x0000000000402183 in printf (__fmt=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/stdio2.h:104
#3  run_drakvuf (data=0x11b6850, user_data=0x402a6d) at dirwatch.c:345
#4  0x00007f27584b02e8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f27584af955 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007f27582286aa in start_thread (arg=0x7f2756169700) at pthread_create.c:333
#7  0x00007f2757f5deed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by zashraf1337** [comment]
This was a false positive I believe.
