### ISSUE TITLE
Python dependency management

### ISSUE THREAD

**Issue by v-p-b** [tklengyel/drakvuf#232]
Python module dependencies can cause some trouble during installation. E.g. I'm on Ubuntu Trusty (same as in install doc) and had to manually disable the distribution provided `setuptools` module in order to get rid of some Rekall errors.

More generally, I think it's best practice to install everything via `pip`. Additionally Rekall even warns when no `virtualenv` is used and it did in fact break during the upgrade to Xen 4.8. I managed to workaround the problem by creating a virtual environment in the submodule directory and run Rekall from there, maybe this should be the preferred way for DRAKVUF installation too.

**Comment by tklengyel** [comment]
Strictly speaking you don't need to have Rekall installed in the same environment where you run DRAKVUF, so whatever works. I'll change the setuptools installation to be done via pip.

**Comment by tklengyel** [comment]
Website updated.

**Comment by amita4581** [comment]
Hi  v-p-b 
as you mentioned in issue 232 dated 26 Dec 2016, i am also facing errors during installation on Ubuntu Trusty.  can you please guide how did you solve it.

rekal convert_profile 4.4.0-59-generic /root/linux.json
Traceback (most recent call last):
  File "/usr/local/bin/rekal", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3030, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3014, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3043, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyparsing==2.1.5' distribution was not found and is required by rekall-core

**Comment by v-p-b** [comment]
I usually do something like this:
```
cd ~/drakvuf/rekall/rekall-core
virtualenv . # Creating virtualenv
bin/activate # Activating environment
pip install setuptools
python setup.py build
```

After this you should be able to use Rekall in the virtualenv. When you're finished, you can deactivate the environment with `deactivate`.

Hope this helps!

**Comment by amita4581** [comment]
appreciate your quick reply..
it seems /drakvuf/rekall/rekall-core/setup.py  mentioned setup is not supporting the virtual env. and it broke at this step

(rekall-core)root@amita-Inspiron-N5110:/home/amita/drakvuf/rekall/rekall-core# python setup.py build
Traceback (most recent call last):
  File "setup.py", line 84, in <module>
    raise RuntimeError("Rekall requires at least setuptool version 8.0. "
RuntimeError: Rekall requires at least setuptool version 8.0. Please upgrade with 'pip install --upgrade setuptools'
(rekall-core)root@amita-Inspiron-N5110:/home/amita/drakvuf/rekall/rekall-core# pip install --upgrade setuptools
Downloading/unpacking setuptools from https://pypi.python.org/packages/a7/62/3995dc3067cbf8d4a13ddac0f87417b9a08799c586b3faa77d62ad9085de/setuptools-34.1.0-py2.py3-none-any.whl#md5=3bd30e82a4371d5fe236c9e412d7b9c6
  Downloading setuptools-34.1.0-py2.py3-none-any.whl (389kB): 389kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/home/amita/drakvuf/rekall/rekall-core/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/amita/drakvuf/rekall/rekall-core/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/amita/drakvuf/rekall/rekall-core/local/lib/python2.7/site-packages/pip/req.py", line 1265, in prepare_files
    req_to_install.extras):
  File "/home/amita/drakvuf/rekall/rekall-core/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2232, in requires
    dm = self._dep_map
  File "/home/amita/drakvuf/rekall/rekall-core/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2423, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/amita/drakvuf/rekall/rekall-core/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2445, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/home/amita/drakvuf/rekall/rekall-core/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2415, in _parsed_pkg_info
    self._pkg_info = Parser().parsestr(self.get_metadata(self.PKG_INFO))
  File "/home/amita/drakvuf/rekall/rekall-core/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 1305, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/home/amita/drakvuf/rekall/rekall-core/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 1414, in _get
    stream = open(path, 'rb')
IOError: [Errno 2] No such file or directory: '/home/amita/drakvuf/rekall/rekall-core/build/setuptools/setuptools-2.2.dist-info/METADATA'

any hint

**Comment by v-p-b** [comment]
It seems `/home/amita/drakvuf/rekall/rekall-core/build/setuptools/setuptools-2.2.dist-info/METADATA` wasn't created. This seems to be unrelated to the Python environment, might be a permission problem, disk full, etc.

**Comment by amita4581** [comment]
thanks again....
i could successfully generate the rekal profile for linux. i feel reason for all these bugs is rekal-core expected pyparsing=2.1.5 and i had 2.1.10 installed auto. diring setup; due to some zip flag error occured while downloading 2.1.5 - so i setup 2.1.5 manually.
