### ISSUE TITLE
Libvmi failed to operate vmi-process-list and showed Rekall profile:no $STRUCTS section found

### ISSUE THREAD

**Issue by Skakf** [tklengyel/drakvuf#373]
Hello, I met a problem when installing the drakvuf.

I installed a Win7_VM on Ubuntu 16.04,Xen4.9

when I used "vmi-win-guid",libvmi works well, while when I tried to operate "vmi-process-list win7"

the result is :

> **The running Xen version is 4.9
> --found Xen
> LibVMI Version 0.11.0
> LibVMI Driver Mode 0
> **The running Xen version is 4.9
> --completed driver init.
> --got id from name (win7 --> 4)
> **set image_type = win7
> **set vm_type HVM
> --xen: setup live mode
> **set allocated_ram_size = 8004b000, max_physical_address = 0xff001000
> **set pae = 1
> **set pse = 1
> **set lme = 1
> **IA-32e paging
> **sanity checking cr3 = 0x0000000000187000
> --looking for config file at /home/ubuntu/Desktop/Drakvuf/drakvuf/libvmi/examples/libvmi.conf
> --looking for config file at /home/ubuntu/etc/libvmi.conf
> --looking for config file at /home/ubuntu/etc/libvmi.conf
> --looking for config file at /etc/libvmi.conf
> **Using config file at /etc/libvmi.conf
> **set os_type to Windows.
> Rekall profile: no $STRUCTS section found
> Failed to init LibVMI library.

The core-issue is that "**Rekall profile: no $STRUCTS section found**"

The pdb I'm using is the file ntkrnlmp.pdb, and the PDB GUID:f8e2a8b5c9b74bf4a6e4a48f180099942

My rekall version: 
This is Rekall Version 1.7.1 (Hurricane Ridge)
{'pep440': u'1.7.1', u'rc': u'0', u'version': u'1.7.1', 'error': 'Not in a git repository.', u'codename': u'Hurricane Ridge', u'post': u'0'}

I tried the following steps:
	rekall -v  fetch_pdb ntkrnlmp f8e2a8b5c9b74bf4a6e4a48f180099942
	rekal -v parse_pdb ntkrnlmp > /tmp/win7.rekall.json

However, the win7.rekall.json doesn't contain the proper $STRUCTS

The $METADATA is :
	$METADATA": {
  	"GUID_AGE": "-5",
 	 "PDBFile": "ntkrnlmp",
  	"ProfileClass": "Ntkrnlmp",
 	 "Timestamp": "2009-07-13 23:40:54Z",
 	 "Type": "Profile",
 	 "Version": 20000404
 	},

I have seen from another issue that maybe there is also  something wrong with my GUID_AGE? 
But I don't know what should I do now.

My python version is python 2.7.12. Should I change it to python3 or another rekall version?

Please help me, Thank you very much!

**Comment by asabellico** [comment]
Use python3 with this rekall version

Il ven 13 apr 2018, 05:33 Skakf <notifications@github.com> ha scritto:

**Comment by rohaaan** [comment]
Any Success using python3??

**Comment by Skakf** [comment]
Thanks for your advice. I am still trying. Some little errors appear and I'm trying to solve. Please wait  for a moment

**Comment by Skakf** [comment]
I am very sorry that when I change to python3.5, I met the problem as below.
The installation of rekall seems no big problems, 
after

> python setup.py build 
> sudo python  setup.py install

when I tried to operate rekal --version, it shows

> Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 9, in <module>
    load_entry_point('rekall-core==1.7.1', 'console_scripts', 'rekall')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/rekall_core-1.7.1-py3.5.egg/rekall/rekal.py", line 41, in <module>
    entry_point.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/rekall_core-1.7.1-py3.5.egg/rekall/plugins/__init__.py", line 4, in <module>
    from rekall.plugins import addrspaces
  File "/usr/local/lib/python3.5/dist-packages/rekall_core-1.7.1-py3.5.egg/rekall/plugins/addrspaces/__init__.py", line 8, in <module>
    from rekall.plugins.addrspaces import ewf
  File "/usr/local/lib/python3.5/dist-packages/rekall_core-1.7.1-py3.5.egg/rekall/plugins/addrspaces/ewf.py", line 26, in <module>
    from rekall.plugins.tools import ewf
  File "/usr/local/lib/python3.5/dist-packages/rekall_core-1.7.1-py3.5.egg/rekall/plugins/tools/__init__.py", line 33, in <module>
    from rekall.plugins.tools import ipython
  File "/usr/local/lib/python3.5/dist-packages/rekall_core-1.7.1-py3.5.egg/rekall/plugins/tools/ipython.py", line 188, in <module>
    class RekallHelper(site._Helper):
AttributeError: module 'site' has no attribute '_Helper'

I feel confused. Could anyone can help me?

Thanks so much!

**Comment by rohaaan** [comment]
> I feel confused. Could anyone can help me?

Even i am stuck at same...

**Comment by Skakf** [comment]
> Use  python3 with this rekall version

Thank you very much !!
I change to python3.5 and the new pdb file contains $STRUCTS.
I can also run vmi-process-list now.  :)
