### ISSUE TITLE
subcon should be a Construct field

### ISSUE THREAD

**Issue by Alibm73** [tklengyel/drakvuf#775]
Hi @tklengyel 
When i run`python3 tools/pdbguid.py /mnt/Windows/System32/ntoskrnl.exe` i get this error:
```python
root@alixen:/home/aliadmin/drakvuf# python3 tools/pdbguid.py /mnt/Windows/System32/ntoskrnl.exe
Traceback (most recent call last):
  File "tools/pdbguid.py", line 122, in <module>
    "Signature" / Const(b"RSDS", Bytes(4)),
  File "/usr/lib/python3/dist-packages/construct/core.py", line 1930, in __init__
    super(Const, self).__init__(subcon)
  File "/usr/lib/python3/dist-packages/construct/core.py", line 288, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field

```

**Comment by tklengyel** [comment]
Yea, I've ran into that myself. It's due to debian's python3-construct package being really old. Just remove that and install it via pip.
```
apt remove python3-construct
pip3 install construct

**Comment by tklengyel** [comment]
I've updated the instructions on the website as well to reflect that it should be installed with pip. I'll close this issue if you can confirm it works for you now too.

**Comment by Alibm73** [comment]
yeah it worked perfectly.
thank you @tklengyel

**Comment by Alibm73** [comment]
altough in this part `python3 ~/drakvuf/volatility3/volatility/framework/symbols/windows/pdbconv.py --guid 684da42a30cc450f81c535b4d18944b12 -p ntkrpamp.pdb -o windows7-sp1.json` i come across this weird error:
```
aliadmin@alixen:/tmp$ python3 ~/drakvuf/volatility3/volatility/framework/symbols/windows/pdbconv.py --guid 4dab61ae88aa44aea1af1fdf42a557e31 -p ntkrnlmp.pdb -o windows7.json
Traceback (most recent call last):
  File "/home/aliadmin/drakvuf/volatility3/volatility/framework/symbols/windows/pdbconv.py", line 13, in <module>
    from volatility.framework import contexts, interfaces, constants
ModuleNotFoundError: No module named 'volatility'
```

**Comment by tklengyel** [comment]
Did you build volatility before you ran the command? Go into the volatility folder and

```
python3 setup.py build

**Comment by Alibm73** [comment]
So i ran the above command as you instructed but:
```
aliadmin@alixen:~/drakvuf/volatility3$ python3 setup.py build
/usr/lib/python3/dist-packages/setuptools/dist.py:397: UserWarning: Normalizing '1.0.0-beta.1' to '1.0.0b1'
  normalized_version,
running build
running build_py
running egg_info
writing volatility.egg-info/PKG-INFO
writing dependency_links to volatility.egg-info/dependency_links.txt
writing entry points to volatility.egg-info/entry_points.txt
writing requirements to volatility.egg-info/requires.txt
writing top-level names to volatility.egg-info/top_level.txt
reading manifest file 'volatility.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'development'
warning: no previously-included files matching 'volatility*.rst' found under directory 'doc/source'
writing manifest file 'volatility.egg-info/SOURCES.txt'
aliadmin@alixen:~/drakvuf/volatility3$ python3 ~/drakvuf/volatility3/volatility/framework/symbols/windows/pdbconv.py --guid 4dab61ae88aa44aea1af1fdf42a557e31 -p ntkrnlmp.pdb -o windows7.json
Traceback (most recent call last):
  File "/home/aliadmin/drakvuf/volatility3/volatility/framework/symbols/windows/pdbconv.py", line 13, in <module>
    from volatility.framework import contexts, interfaces, constants
ModuleNotFoundError: No module named 'volatility'
aliadmin@alixen:~/drakvuf/volatility3$
```

**Comment by tklengyel** [comment]
Yea, looks like you must also install it:
```
python3 setup.py install

**Comment by Alibm73** [comment]
@tklengyel it worked, thanks
you can close the issue if you want
