### ISSUE TITLE
libxl: error: libxl_create.c:671 | libxl_create.c:1233 | [ERROR] Failed to launch VM vm-0

### ISSUE THREAD

**Issue by filipi86** [tklengyel/drakvuf#974]
Hi Everyone
I'm trying to use the drakvuf sandbox and I'v received the same error in my installations..

I tried:
Ubuntu 18.04 
Debian 10..

but appears the same error in both of than.

Installation based on based packages ( .deb like recommendation here in github) 

Error:

[2020-08-26 10:02:09,892][INFO] Ensuring that drakrun@* services are stopped...
[2020-08-26 10:02:09,905][INFO] Performing installation...
[2020-08-26 10:02:26,070][INFO] Checking xen-detect...
Running in PV context on Xen V4.14.
[2020-08-26 10:02:26,082][INFO] Testing if xl tool is sane...
[2020-08-26 10:02:26,145][INFO] Generated VM configuration for vm-0
Parsing config from /etc/drakrun/configs/vm-0.cfg
libxl: error: libxl_create.c:671:libxl__domain_make: domain creation fail: Invalid argument
libxl: error: libxl_create.c:1233:initiate_domain_create: cannot make domain: -3
[2020-08-26 10:02:26,246][ERROR] Failed to launch VM vm-0
Traceback (most recent call last):
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 163, in install
    subprocess.run('xl create {}'.format(shlex.quote(cfg_path)), shell=True, check=True)
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'xl create /etc/drakrun/configs/vm-0.cfg' returned non-zero exit status 3.

![drakvuf](https://user-images.githubusercontent.com/31785433/91330433-cccc9f80-e79f-11ea-8e95-90098ecc6f4b.png)

Do you have any idea or suggestion?

Best Regards,
Filipi Pires

**Comment by filipi86** [comment]
> /cc @icedevml I think this error belongs to https://github.com/CERT-Polska/drakvuf-sandbox

I opened in both channel. :)

**Comment by icedevml** [comment]
resolved here https://github.com/CERT-Polska/drakvuf-sandbox/issues/220
